-- скрипт создания объектов для приведеной модели тестового задания
-- исполнитель [JINT] (SHIFT-68275) Дойников Никита Александрович

-- Создание таблиц
-- Создание таблицы [CLIENTS] – таблица содержит основную информацию по клиентам Банка
DROP TABLE IF EXISTS clients CASCADE; -- удаление каскадом только в рамках тестового задания

CREATE TABLE clients (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- уникальный идентификатор
    name VARCHAR(255),                                   -- ФИО клиента
    place_of_birth VARCHAR(255),                         -- Место рождения клиента
    date_of_birth DATE,                                  -- Дата рождения клиента
    address VARCHAR(255),                                -- Адрес проживания клиента
    passport VARCHAR(100)                                -- Паспортные данные клиента
);

-- Создание таблицы [TARIFS] – таблица содержит информацию о тарифах за операции по счетам
DROP TABLE IF EXISTS tarifs CASCADE;

CREATE TABLE tarifs (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- уникальный идентификатор
    name VARCHAR(100) NOT NULL,                          -- наименование тарифа
    cost NUMERIC(15, 2) NOT NULL                         -- сумма тарифа
);

-- Создание таблицы [PRODUCT_TYPE] -  таблица содержит информацию о типах продуктов, которые доступны для открытия клиенту
DROP TABLE IF EXISTS product_type CASCADE;

CREATE TABLE product_type (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- уникальный идентификатор
    name VARCHAR(100),                                   -- наименование типа продукта
    begin_date DATE,                                     -- дата начала действия типа продукта
    end_date DATE,                                       -- дата окончания действия типа продукта
    tarif_ref INT,                                       -- ссылка на тариф
    CONSTRAINT prod_type_tar_fk FOREIGN KEY (tarif_ref)
        REFERENCES tarifs(id)
        ON DELETE CASCADE                                -- Удаление типов продуктов при удалении тарифа
);

-- Создание таблицы [PRODUCTS] – таблица содержит информацию о продуктах, открытых для клиента в Банке
DROP TABLE IF EXISTS products CASCADE;

CREATE TABLE products(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- уникальный идентификатор
    product_type_id INT,                                 -- ссылка на тип продукта
    name VARCHAR,                                        -- наименование продукта
    client_ref INT,                                      -- ссылка на клиента
    open_date DATE,                                      -- дата открытия продукта
    close_date DATE,                                     -- дата закрытия продукта
    CONSTRAINT prod_cl_fk FOREIGN KEY (client_ref) 
        REFERENCES clients(id)
        ON DELETE CASCADE,      -- при удалении клиента удаляются все связанные продукты
    CONSTRAINT prod_prodtype_fk FOREIGN KEY (product_type_id)
        REFERENCES product_type(id)
        ON DELETE CASCADE       -- при удалении продукта удалится таблица с типом продукта
);

-- Создание таблицы [ACCOUNTS] -  таблица содержит информацию о счетах, открытых для клиента в Банке
DROP TABLE IF EXISTS accounts CASCADE;

CREATE TABLE accounts (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- уникальный идентификатор
    name VARCHAR(100),                                   -- наименование счета
    saldo NUMERIC(15, 2),             					 -- остаток по счету
    client_ref INT,                                      -- ссылка на клиента
    open_date DATE,                                      -- дата открытия счета
    close_date DATE,                                     -- дата закрытия счета
    product_ref INT,                                     -- ссылка на продукт, в рамках которого открыт счет
    acc_num VARCHAR(25),                                 -- номер счета
    CONSTRAINT acc_num_uk  UNIQUE(acc_num),              -- счет делаю уникальным
    CONSTRAINT acc_cl_fk FOREIGN KEY (client_ref)
        REFERENCES clients(id)
        ON DELETE SET NULL,                              -- удаленный клиент не удалит запись о созданных счетах
    CONSTRAINT acc_prod_fk FOREIGN KEY (product_ref)
        REFERENCES products(id)
        ON DELETE SET NULL                               -- удаленный продукт не удалит запись о счетах
);


-- Создание таблицы [RECORDS] – таблица содержит информацию операциях по счетам
DROP TABLE IF EXISTS records CASCADE;

CREATE TABLE records (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- уникальный идентификатор
    dt INT CHECK (dt IN (0, 1)),                         -- 1 - дебет, остаток по счету уменьшается. 0 - кредит, остаток по счету увеличивается
    sum NUMERIC(15, 2) NOT NULL,                         -- сумма операции
    acc_ref INT,                                         -- ссылка на счет, по которому происходит движение
    oper_date DATE NOT NULL,                             -- дата операции
    CONSTRAINT rec_acc_fk FOREIGN KEY (acc_ref)
        REFERENCES accounts(id)
        ON DELETE SET NULL
);


